on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: npm install
      run: npm install &&
        npm audit fix

    - name: create xpi
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET:{{ secrets.API_SECRET }}
      run: npm run pack:ff

    - name: setup ftp
      run: sudo apt-get install lftp




      
        
